"use strict";
let loc = {
    "attack_anvil": "was crushed by an anvil",
    "attack_arrow": "was aimbotted to death by klr",
    "attack_arrow_item": "was sniped by klr",
    "attack_cactus": "was cactus'd to death",
    "attack_cactus_player": "was cactus'd to death whilst trying to escape klr",
    "attack_drown": "is sleeping with the fishes",
    "attack_drown_player": "drowned whilst trying to escape klr",
    "attack_explosion": "blew up... literally",
    "attack_explosion_player": "was nuked by klr",
    "attack_fall": "fell from the 13th floor and died",
    "attack_fallingblock": "didn't get out of the way of a falling block in time",
    "attack_fireball": "was fireballed by klr",
    "attack_fireball_item": "was turned to ash by klr's fireball",
    "attack_fireworks": "celebrated the 4th of july early this year",
    "attack_flyintowall": "flew straight into a wall at ballistic speeds",
    "attack_freeze": "got turned into a player-sicle",
    "attack_generic": "died under very mysterious circumstances...",
    "attack_indirectmagic": "was killed by klr using belkan witchcraft",
    "attack_indirectmagic_item": "was killed by klr's avada kedavara",
    "attack_infire": "was cooked to perfection!",
    "attack_infire_player": "was cooked to perfection by klr!",
    "attack_inwall": "was buried alive",
    "attack_lava": "took a dip in the (really) hot tub",
    "attack_lava_player": "jumped into lava to escape klr",
    "attack_lightningbolt": "was struck by lightning",
    "attack_magic": "was killed using arcane magic",
    "attack_magma": "was pretending the floor was lava, but discovered it was actually magma",
    "attack_magma_player": "walked into the *danger zone* fighting klr",
    "attack_mob": "was tragically slain by klr",
    "attack_onfire": "learned why you shouldn't play with matches",
    "attack_onfire_player": "was roasted when klr channeled their inner blaze",
    "attack_outofworld": "fell into the infinite abyss",
    "attack_player": "was pwned by klr",
    "attack_player_item": "got pwned by klr",
    "attack_spit": "died from a critical hit with a killer loogie",
    "attack_stalactite": "was skewered by a falling stalactite",
    "attack_stalagmite": "was impaled on a stalagmite",
    "attack_starve": "died on an empty stomach",
    "attack_testing": "probably some other stuff too idk",
    "attack_thorns": "was killed by recoil damage while attacking klr",
    "attack_thrown": "was pummeled by klr",
    "attack_thrown_item": "was pummeled by klr",
    "attack_trident": "was forked to death by klr",
    "attack_wither": "withered away",
    "entity_allay_name": "allay lmao",
    "entity_bee_name": "bee",
    "entity_blaze_name": "blaze",
    "entity_cave_spider_name": "cave spider",
    "entity_creeper_name": "creeper",
    "entity_dolphin_name": "dolphin",
    "entity_dragon_fireball_name": "dragon fireball",
    "entity_drowned_name": "drowned",
    "entity_elder_guardian_name": "elder guardian",
    "entity_ender_dragon_name": "ender dragon",
    "entity_enderman_name": "enderman",
    "entity_endermite_name": "endermite",
    "entity_evocation_fang_name": "evoker fangs",
    "entity_evocation_illager_name": "evoker",
    "entity_frog_name": "frog",
    "entity_ghast_name": "ghast",
    "entity_goat_name": "goat",
    "entity_guardian_name": "guardian",
    "entity_hoglin_name": "hoglin",
    "entity_husk_name": "husk",
    "entity_iron_golem_name": "iron golem",
    "entity_llama_name": "llama",
    "entity_llama_spit_name": "llama spit",
    "entity_magma_cube_name": "magma cube",
    "entity_panda_name": "panda",
    "entity_phantom_name": "phantom",
    "entity_piglin_brute_name": "piglin brute",
    "entity_piglin_name": "piglin",
    "entity_pillager_name": "pillager",
    "entity_polar_bear_name": "polar bear",
    "entity_pufferfish_name": "pufferfish",
    "entity_ravager_name": "ravager",
    "entity_shulker_bullet_name": "shulker bullet",
    "entity_shulker_name": "shulker",
    "entity_silverfish_name": "silverfish",
    "entity_skeleton_horse_name": "skeleton horse",
    "entity_skeleton_name": "skeleton",
    "entity_slime_name": "slime",
    "entity_spider_name": "spider",
    "entity_stray_name": "stray",
    "entity_vex_name": "vex",
    "entity_vindicator_name": "vindicator",
    "entity_warden_name": "warden",
    "entity_witch_name": "witch",
    "entity_wither_name": "wither",
    "entity_wither_skeleton_name": "wither skeleton",
    "entity_wither_skull_dangerous_name": "wither skull",
    "entity_wither_skull_name": "wither skull",
    "entity_wolf_name": "wolf",
    "entity_zoglin_name": "zoglin",
    "entity_zombie_name": "zombie",
    "entity_zombie_pigman_name": "zombified piglin",
    "entity_zombie_villager_name": "zombie villager",
    "entity_zombie_villager_v2_name": "zombie villager",
    "fell_accident": "went ***splat!***",
    "fell_accident_generic": "went ***splat!***",
    "fell_accident_killer": "went ***splat*** whilst trying to outrun death",
    "fell_accident_ladder": "fell off a ladder and went ***splat!***",
    "fell_accident_vines": "was trying to be tarzan and went ***splat!***",
    "fell_accident_water": "missed the puddle and went ***splat!***",
    "attack_sonicboom_player": "got straight-up owned by the warden's sonic boom",
    "entity_sc_blazebasalto_name": "basalt blaze",
    "entity_sc_blazecarmesi_name": "crimson blaze",
    "entity_sc_blazeretorcido_name": "warped blaze",
    "entity_sc_blazesould_name": "soul blaze",
    "entity_sc_cthulhu_name": "eye of cthulu",
    "entity_sc_demonio_blood_name": "demonic blood ghast",
    "entity_sc_demonio_name": "demonic soul ghast",
    "entity_sc_golem_carmesi2_name": "semi-crimson golem",
    "entity_sc_golem_carmesi_name": "crimson golem",
    "entity_sc_golem_retorcido2_name": "semi-warped golem",
    "entity_sc_golem_retorcido_name": "warped golem ",
    "entity_sc_hongo_carmesi_name": "pet crimson mushroom",
    "entity_sc_hongo_carmesiblack_name": "crimson black mushroom",
    "entity_sc_hongo_torcido_name": "pet warped mushroom",
    "entity_sc_hongo_torcidoblack_name": "black warped mushroom",
    "entity_sc_pig_nethercandy2_name": "warped pig",
    "entity_sc_pig_nethercandy3_name": "basalt pig",
    "entity_sc_pig_nethercandy4_name": "soul pig",
    "entity_sc_pig_nethercandy_name": "crimson pig ",
    "entity_tt_bloodymeat_name": "mini-boss bloody meat",
    "entity_tt_creeper_magmatico_name": "nuclear creeper",
    "entity_tt_creeper_magmatico_retorcido_name": "warped nuclear creeper",
    "entity_tt_creeper_pet_crimson_name": "crimson creeper pet",
    "entity_tt_creeper_pet_twisted_name": "warped creeper pet",
    "entity_tt_creepycreeper_name": "creepy creeper",
    "entity_tt_crimsoncreeper_name": "crimson creeper",
    "entity_tt_infernalgolem_name": "infernal golem",
    "entity_tt_petblackstone_name": "pet blackstone",
    "entity_tt_petcarmesi_name": "pet crimson",
    "entity_tt_pettwisted_name": "pet warped",
    "entity_tt_soulstrider_name": "soul strider",
    "entity_tt_twistedcreeper_name": "warped creeper"
};
module.exports = loc;
